---
# tasks file for ansible-role-user
- name: add a new user
  user: name={{ user.name }} password={{ user.password }} state=present
  # when: {{ user.name }}

- name: mkdir .ssh          #.sshフォルダの作成
  file: dest=/home/{{ user.name }}/.ssh/ state=directory owner={{ user.name }} group={{ user.name }} mode=700
  # when: {{ user.name }}

- name: add authorized keys #.ssh以下にauthorized_keysファイルの作成
  file: dest=/home/{{ user.name }}/.ssh/authorized_keys state=touch owner={{ user.name }} group={{ user.name }} mode=600
  # when: {{ user.name }}

- name: no password
  lineinfile: dest=/etc/sudoers.d/{{ user.name }} line="{{ user.name }} ALL=(ALL) NOPASSWD:ALL" create=yes owner=root group=root mode=0440

- name: copy publickey     #公開鍵を貼付け
  copy: src={{ user.id_rsa_pub_path }} dest=/home/{{ user.name }}/.ssh/authorized_keys
  # when: {{ user.name }}
